language: java

jdk:
  - oraclejdk8

script:
  # executing the Junit tests
  - mvn test
  # also testing the main outside Junit
  - mvn exec:java -Dexec.mainClass="experiment.Main2" -Dexec.args="-v -s quicksort.QuickSortManager -nb 4 -size 4 -exp call pone"
  - mvn exec:java -Dexec.mainClass="experiment.Main2" -Dexec.args="-v -s quicksort.QuickSortManager -nb 4 -size 4 -exp rnd pone"
